services:
  advisor:
    class: 'PhpMyAdmin\Advisor'
    arguments:
      dbi: '@dbi'
      expression_language: '@expression_language'

  config:
    class: 'PhpMyAdmin\Config'
    arguments: [!php/const CONFIG_FILE]

  create_add_field:
    class: 'PhpMyAdmin\CreateAddField'
    arguments: ['@dbi']

  designer:
    class: 'PhpMyAdmin\Database\Designer'
    arguments:
      dbi: '@dbi'
      relation: '@relation'
      template: '@template'

  designer_common:
    class: 'PhpMyAdmin\Database\Designer\Common'
    arguments:
      dbi: '@dbi'
      relation: '@relation'

  error_handler:
    class: 'PhpMyAdmin\ErrorHandler'

  error_report:
    class: 'PhpMyAdmin\ErrorReport'
    arguments: ['@http_request', '@relation', '@template']

  export:
    class: 'PhpMyAdmin\Export'
    arguments: ['@dbi']

  expression_language:
    class: 'Symfony\Component\ExpressionLanguage\ExpressionLanguage'

  http_request:
    class: 'PhpMyAdmin\Utils\HttpRequest'

  import:
    class: 'PhpMyAdmin\Import'

  navigation:
    class: 'PhpMyAdmin\Navigation\Navigation'
    arguments: ['@template', '@relation', '@dbi']

  normalization:
    class: 'PhpMyAdmin\Normalization'
    arguments:
      dbi: '@dbi'
      relation: '@relation'
      transformations: '@transformations'
      template: '@template'

  relation:
    class: 'PhpMyAdmin\Relation'
    arguments: ['@dbi', '@template']

  replication:
    class: 'PhpMyAdmin\Replication'

  replication_gui:
    class: 'PhpMyAdmin\ReplicationGui'
    arguments:
      replication: '@replication'
      template: '@template'

  response:
    factory: 'PhpMyAdmin\Response::getInstance'

  sql_query_form:
    class: 'PhpMyAdmin\SqlQueryForm'

  status_data:
    class: 'PhpMyAdmin\Server\Status\Data'

  status_monitor:
    class: 'PhpMyAdmin\Server\Status\Monitor'
    arguments: ['@dbi']

  template:
    class: 'PhpMyAdmin\Template'

  tracking:
    class: 'PhpMyAdmin\Tracking'
    arguments:
      sql_query_form: '@sql_query_form'
      template: '@template'
      relation: '@relation'

  transformations:
    class: 'PhpMyAdmin\Transformations'

  #Aliases

  PhpMyAdmin\Response: '@response'

  PhpMyAdmin\DatabaseInterface: '@dbi'